# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 705b099dc992af5f36bd10459df56b91887fe60022c4af0523fc5e3662a4b42741027187ef037a34ffa556c2bbc490ba109973dfcfa4a052ae4ce497591f5599

test:
  secret_key_base: 42f2c65f88f6b41ec1ab7059c66e53e3b2e7dd18edc17f3a5bd34411c618de519f874a0202af34fa8437c83dc1e98d7440e9bee1c2cd29c4aed9d6d0764e1f13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
